routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.index');
});



// Auth::routes();

// Route::get('/home', 'HomeController@index');


Route::resource('logins', 'LoginController');
Route::post('login', 'LoginController@login');

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        Index
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <link rel="stylesheet" href="../fa-5/web-fonts-with-css/css/fontawesome-all.css">
    <link rel="stylesheet" href="../css/reset.css">
    <link rel="stylesheet" href="../css/font.css">
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="../css/responsive.css">
</head>
<body>
  <!-- HEADER -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 header">
                <span class="logo-header">
                    <img src="../asset/image/logo-header.png">
                </span>
            </div>
        </div>
<!-- MAIN-KONTEN -->

    <div class="row">
      <!-- =========================== RIGHT KONTEN ================ -->
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2" style="padding: 0;">
              <div class="nav-side-menu">
                <div class="brand"></div>
                  <div class="menu-list">
                    <ul id="menu-content" class="menu-content collapse out">
                        <!-- <li data-toggle="collapse" data-target="#service" class="collapsed">
                          <a href="#"><i class="fa fa-globe fa-lg"></i> Services <span class="arrow"></span></a>
                        </li>
                        <ul class="sub-menu collapse" id="service">
                          <li>New Service 1</li>
                          <li>New Service 2</li>
                          <li>New Service 3</li>
                        </ul> -->
                        <li>
                          <a href="admin_index.php"><i class="fa fa-home" aria-hidden="true"></i> Home</a>
                        </li>
                        <li>
                          <a href="admin_guru.php"><i class="fa fa-id-badge" aria-hidden="true"></i> Data Guru</a>
                        </li>
                        <li>
                          <a href="admin_siswa.php"><i class="fa fa-id-card" aria-hidden="true"></i> Data Siswa</a>
                        </li>
                        <li>
                          <a href="admin_jurusan.php"><i class="fa fa-sitemap" aria-hidden="true"></i> Jurusan</a>
                        </li>
                        <li>
                          <a href="admin_kelas.php"><i class="fa fa-users" aria-hidden="true"></i> Kelas</a>
                        </li>
                        <li>
                          <a href="admin_ajaran.php"><i class="fa fa-book" aria-hidden="true"></i> Tahun Ajaran</a>
                        </li>
                        <li>
                          <a href="../php/logout.php"><i class="fa fa-sign-out-alt" aria-hidden="true"></i> Logout</a>
                        </li>
                    </ul>
                </div>
              </div>
            </div>
      <!-- =============================== LEFT KONTEN ===================== -->

          @yield('content')
        </div>
        <div class="clear"></div>
        <div class="footer">
            Copyright&copy; SMK Tunas Media. Created by Danang Widianto
        </div>
        <!-- Script -->
            <script src="../js/jquery.min.js"></script>
            <script type="text/javascript" src="../js/popper.min.js"></script>
            <script type="text/javascript" src="../js/bootstrap.min.js"></script>
            <script type="text/javascript" src="../js/jquery-ui.js"></script>
            <script type="text/javascript" src="../js/main.js"></script>
            <script type="text/javascript">
                $(".collapse").slideToggle(".sub-menu");
            </script>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
	<title>
	@yield('title')
	</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	@include('layouts.css')
	@yield('css')

</head>

<body>
	<!-- HEADER -->
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 header">
				<span class="logo-header">
					<img src="{{('img/logo-header.png')}}">
				</span>
				@yield('dropdown-right')
			</div>
		</div>
		<!-- MAIN-KONTEN -->
		@yield('content')


	</div>
	<!-- Script -->
	@include('layouts.js')
	@yield('script')
</body>

</html>

resources/views/layouts/css.blade.php
<link rel="stylesheet" href="{{url('css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{url('css/fa/css/font-awesome.min.css')}}">
<link rel="stylesheet" href="{{url('css/fa-5/web-fonts-with-css/css/fontawesome-all.css')}}">
<link rel="stylesheet" href="{{url('css/reset.css')}}">
<link rel="stylesheet" href="{{url('css/font.css')}}">
<link rel="stylesheet" href="{{url('css/style.css')}}">
<link rel="stylesheet" href="{{url('css/responsive.css')}}">

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/dropdown-right.blade.php
<span class="nama-header">
    <div class="dropdown show">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #100021;">
        Test
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <a class="dropdown-item" href="../php/logout.php">Logout</a>
      </div>
    </div>
  </span>

resources/views/layouts/js.blade.php
<script src="{{url('js/jquery.min.js')}}"></script>
<script type="text/javascript" src="{{url('js/popper.min.js')}}"></script>
<script type="text/javascript" src="{{url('js/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{url('js/jquery-ui.js')}}"></script>
<script type="text/javascript" src="{{url('js/main.js')}}"></script>

resources/views/layouts/menu.blade.php
<li class="{{ Request::is('logins*') ? 'active' : '' }}">
    <a href="{!! route('logins.index') !!}"><i class="fa fa-edit"></i><span>Logins</span></a>
</li>

resources/views/layouts/right-konten-admin.blade.php
<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2" style="padding: 0;">
        <div class="nav-side-menu">
          <div class="brand"></div>
            <div class="menu-list">
              <ul id="menu-content" class="menu-content collapse out">
                  <!-- <li data-toggle="collapse" data-target="#service" class="collapsed">
                    <a href="#"><i class="fa fa-globe fa-lg"></i> Services <span class="arrow"></span></a>
                  </li>
                  <ul class="sub-menu collapse" id="service">
                    <li>New Service 1</li>
                    <li>New Service 2</li>
                    <li>New Service 3</li>
                  </ul> -->
                  <li>
                    <a href="admin_index.php"><i class="fa fa-home" aria-hidden="true"></i> Home</a>
                  </li>
                  <li>
                    <a href="admin_guru.php"><i class="fa fa-id-badge" aria-hidden="true"></i> Data Guru</a>
                  </li>
                  <li>
                    <a href="admin_siswa.php"><i class="fa fa-id-card" aria-hidden="true"></i> Data Siswa</a>
                  </li>
                  <li>
                    <a href="admin_jurusan.php"><i class="fa fa-sitemap" aria-hidden="true"></i> Jurusan</a>
                  </li>
                  <li>
                    <a href="admin_kelas.php"><i class="fa fa-users" aria-hidden="true"></i> Kelas</a>
                  </li>
                  <li>
                    <a href="admin_ajaran.php"><i class="fa fa-book" aria-hidden="true"></i> Tahun Ajaran</a>
                  </li>
                  <li>
                    <a href="../php/logout.php"><i class="fa fa-sign-out-alt" aria-hidden="true"></i> Logout</a>
                  </li>
              </ul>
          </div>
        </div>
      </div>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>